Реактик подъехал
VolffS/ToDoList pull request #4
Opened 2024-03-07 07:26 UTC by VolffS

Ругайте! Но не сильно я ранимый)

2024-03-07 16:59 UTC, xDSUP commented on src/client/scripts/features/helpers.js
> +module.exports = {
такая запись не позволяет нормально посмотреть, где используются эти функции. Лучше использовать инлайн export в стиле es6

2024-03-07 17:00 UTC, xDSUP commented on src/client/scripts/features/helpers.js
> +function filterByStatus(tasks, filter) {
export function ... и сейчас бест практис использовать стрелочные функции 

export const filterByStatus = () => {}

2024-03-07 17:02 UTC, xDSUP commented on src/client/scripts/features/helpers.js
> +function changeStyleCSS( selector, property, value ) {
давай подумаем, как отказаться от этой функции и не взаимодейстовать с деревом и style.setProperty напрямую

2024-03-07 17:02 UTC, xDSUP commented on src/client/scripts/features/helpers.js
> +function findParentTask(element) {
Таже фигнюшка, надо это убрать

2024-03-07 17:03 UTC, xDSUP commented on src/client/scripts/features/crud.js
> +export function changeStatusTask(tasks, element) {
тоже самое)

2024-03-07 17:09 UTC, xDSUP commented on src/client/scripts/features/crud.js
> +        toDoList.selectTasksId = [toDoList.selectTasksId];
если хочешь чет вот так передавать, лучше, когда кладешь в обьект 1 элемент, сразу его в массив обернуть. Старайся, чтобы не было двойственности в типе свойства - (у тебя это и id и массив id одновременно может быть)

2024-03-07 17:09 UTC, xDSUP commented on src/client/scripts/features/crud.js
> +    requestToServer('DELETE', toDoList.selectTasksId)
по хорошему на 3 разных запроса бы разбить. с соответствующими названиями

2024-03-07 17:24 UTC, xDSUP commented on src/client/scripts/script.js
> +            ? <ModifyTask {...{value: props.value, modifyCallback, switchModify}}/>
пропсы лучше в обычном виде прокидывать : 

<ModifyTask value={props.value} modifyCallback={modifyCallback} switchModify={switchModify}/>

2024-03-07 17:27 UTC, xDSUP commented on src/client/scripts/script.js
> +                : <Spinner />}
очень сложный тернарник для восприяния, если хочешь спиннер, отрендери его уж в самом начале, а потом уже замену вместо него 
чет типо такого :
{ !task && <Spinner />}
{ task && stateModifyTask
? <ModifyTask />
: <StaticTask />
}

2024-03-07 17:28 UTC, xDSUP commented on src/client/scripts/script.js
> +            : task !== ""
давай теперь пользоваться правилом 1 компонент - 1 файл
task -> task.jsx

2024-03-07 17:30 UTC, xDSUP commented on src/index.js
> +const listToDo = document.querySelector("main.container");
все файлы, где есть какой-нибудь компонент должны быть с типом jsx)

2024-03-07 17:31 UTC, xDSUP commented on src/client/scripts/script.js
> +import ReactDOM from 'react-dom';
импорт не используется, можно дропнуть, и так в других фаилах, в идее для этого горячие клавиши есть, если что

2024-03-07 17:32 UTC, xDSUP commented on src/client/scripts/script.js
> +        changeStyleCSS('.delete-checkBox', 'display', 'none');
вот от этой гадости бы уйти)

2024-03-07 17:33 UTC, xDSUP commented on src/client/scripts/script.js
> +                        : stateToDoList.tasks.length !== 0
сложно для восприятия

2024-03-07 17:47 UTC, xDSUP requested changes

2024-03-07 17:47 UTC, xDSUP commented on src/client/scripts/script.js
> +                        <select onChange={(ev)=>{filterTask(ev.target.value)}} className="form-select " id="sort-status">
попробуй вынести этот селект в отдельный комопнент

2024-03-07 17:47 UTC, xDSUP commented on src/client/scripts/script.js
> +    let deleteCallback = props.deleteBtnTask;
не используется

2024-03-07 17:50 UTC, xDSUP commented
Давай все-таки немного иначе делать, 
сейчас летит запрос на сервер и мы дублируем изменения на фронте
а нужно все-таки: делаем запрос на серв и затем перезапрашиваем данные

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/script.js
> +        changeStyleCSS('.delete-checkBox', 'display', 'none');
done

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/script.js
> +import ReactDOM from 'react-dom';
done

2024-03-08 15:26 UTC, VolffS commented on src/index.js
> +const listToDo = document.querySelector("main.container");
Сейчас не возможно

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/script.js
> +            : task !== ""
done

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/script.js
> +                : <Spinner />}
done

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/script.js
> +            ? <ModifyTask {...{value: props.value, modifyCallback, switchModify}}/>
done

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/features/crud.js
> +    requestToServer('DELETE', toDoList.selectTasksId)
done

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/features/crud.js
> +        toDoList.selectTasksId = [toDoList.selectTasksId];
done

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/features/crud.js
> +export function changeStatusTask(tasks, element) {
done

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/features/helpers.js
> +function findParentTask(element) {
done

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/features/helpers.js
> +function changeStyleCSS( selector, property, value ) {
done

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/features/helpers.js
> +function filterByStatus(tasks, filter) {
done

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/features/helpers.js
> +module.exports = {
done

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/script.js
> +                        : stateToDoList.tasks.length !== 0
done

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/script.js
> +                        <select onChange={(ev)=>{filterTask(ev.target.value)}} className="form-select " id="sort-status">
done

2024-03-08 15:26 UTC, VolffS commented on src/client/scripts/script.js
> +    let deleteCallback = props.deleteBtnTask;
done

2024-03-08 16:02 UTC, merged